name: Scheduled Auto Merge

on:
  schedule:
    - cron: "40 14 * * 0"
  workflow_dispatch:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge PRs with schedule_merge label
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
            });

            for (const pr of prs) {
              const hasLabel = pr.labels.some(l => l.name === "schedule_merge");
              if (!hasLabel || pr.draft) continue;

              const { data: reviews } = await github.rest.pulls.listReviews({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
              });

              const approved = reviews.some(r => r.state.toLowerCase() === "approved");
              const changesRequested = reviews.some(r => r.state.toLowerCase() === "changes_requested");
              if (!approved || changesRequested) continue;

              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: "squash",
              });
            }
